### ISSUE TITLE
Issue template to submit learning materials

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiverse-trace.github.io#206]
@Bisaloo previously proposed an issue template to submit learning materials in #157. After changes, it was unclear whether we want this as a template, and @avallecam proposed to further discuss this in an issue. 

The question is whether we accept submitted learning materials, and if so, whether we want to accept them through issues or any other means. If we accept them through issues, it is also a question whether the template includes all the information we need.

Given that this issue was requested by @avallecam, I am assigning it to them for the time being.

<details>
  <summary>Previously proposed template</summary>

```
name: Submit learning material
description: A form for the community to submit learning materials for inclusion on the `Learn` page. 
title: "[Learn]: "
labels: ["good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your learning material for Epiverse!
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the title of the learning material? Preferably < 150 characters
      placeholder: Using Epiverse for the first time
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your material
      description: What can help people understand whether this is relevant learning material for them?
      placeholder: Here we walk you through all the steps to use Epiverse for the first time.
    validations:
      required: false
  - type: input
    id: img
    attributes:
      label: Cover image
      description: Provide us with a link to an image that we can use for this. A screenshot for example.
      placeholder: https://example.com/img.png
    validations:
      required: true
  - type: textarea
    id: authors
    attributes:
      label: Who are the authors?
      description: Share who created the learning materials. Please separate authors with a comma.
      placeholder: Author 1, Author 2
    validations:
      required: true
  - type: textarea
    id: categories
    attributes:
      label: What keywords do you want associated with this?
      description: This will help people find your materials. Please separate with a comma.
      placeholder: Keyword 1, Keyword2
    validations:
      required: false
  - type: input
    id: lang
    attributes:
      label: What language are these materials in?
      placeholder: English
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue you grant us the right to post the materials if they are relevant for Epiverse. You understand we do not guarantee posting.
      options:
        - label: I agree and understand that you may post the content I submit here.
          required: true
```
</details>
